修改启动报错 1> WARN  [main:AdminServerFactory@58] - Unable to load jetty, not starting JettyAdminServer 2> java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir    zookeeper3.6版本使用的metrics-core 的scope provide 注掉 3> Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyInputStream    pom.xml中snappy-java的scope为provided，把它直接注释掉问题可以得到解决